ladybuzz/N2-reprograma-CV

index.html, students/mariana_mercier/mariana_mercier.html
=> renomeando arquivos

index.html, students/claudia_prudente/claudia_prudente.html
=> primeira modificação claudia

index.html, students/luiza-araujo/luiza-araujo.html
=> iniciando cv luiza-araujo

students/luiza-araujo/luiza-araujo.html
=> finalizando CV luiza-araujo

index.html, students/renata_carvalho/renata_carvalho.html
=> Linkei links e renomeei arquivos

1111.txt, index.html, students/ana-paula-rossini/cv_template.html
=> Informações Adicionadas (Ana Paula Rossini)

index.html, students/manoela-zulian/manoela-zulian.html
=> Adicionar o nome da Manoela Zulian

index.html, students/mariana-oliveira/mariana-oliveira.html
Primeiro pull request (mariana oliveira)
=> Mariana oliveira

index.html, students/catarina-manzieri/catarina-manzieri.html
=> Inserção de dados para contato

index.html, students/thassia-lima/thassia-lima.html
=> primeiras alterações

index.html, students/Ester_Leal/Ester_Leal.html
Renomeando arquivos com o nome de estudante.
=> Renomear aquivos para o nome de estudante

index.html, students/carolina-estrela/carolina-estrela.html
=> First commit

index.html, students/nilce-watace/nilce-watace.html
Uh... okay, well, the button on the side, is it glowing?
=> Hello, IT. Have you tried turning it off and on again?

index.html, students/gabrielle-santos/gabrielle-santos.html
Meu primeiro pull request hee o/
=> Renomeando arquivos e pastas

students/fabiana-ferlin/fabiana-ferlin.html
=> Criando arquivo fabiana-ferlin

index.html, students/loreny_ielpo/loreny_ielpo.html
=> renomeando os arquivos

index.html, students/priscilla-camillo/priscilla-camillo.html
1 - atualizacao de Nome, Email, O que quero
=> CV adicionado Nome Email Quero

index.html, students/andressa-tancredi/andressa-tancredi.html
=> Primeiro Commit

index.html, students/milena-melguiso/milena-melguiso.html
Adicionando minhas informações
Jô MARAVILHOSAAAAAA
=> Renomear arquivo 25 para Milena Melguiso e adicionar informações

index.html, students/suelen_quadros/suelen-quadros.html
=> renomeado arquivos

students/andressa-tancredi/andressa-tancredi.html
Conteúdo parcial do CV. Ainda falta uma parte que vou completar até o dia 10.
Beijo
=> Altera conteúdo

students/andressa-tancredi/andressa-tancredi.html
Olá Prof !! 
Este é meu commit final.
Obrigada =)
=> Entrega final

index.html, students/kelly-christina/kelly-christina.html
preenchimento de dados de Kelly Christina
=> preenchimento de dados

students/milena-melguiso/cv-milena-melguiso.css, students/milena-melguiso/milena-melguiso.html
=> Interesses, apresentação - conclusão final

students/juliana-kim/juliana-kim.html
=> julianakim_cv ok

students/bianca-faial4/bianca-faial.html
modificação das divs e inserção de cursos
=> Bianca faial

students/thassia-lima/thassia-lima.html
Olar sua linda, segue meu CV bem desconfigurado hahahaha
=> Thassia lima

students/gabrielle-santos/gabrielle-santos.html
Não está completo o campo "No que já trabalhei" e o campo "Meus outros aprendizados e interesses"
=> Modifiquei  curriculo Gabrielle-santos
